### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by asadmisrani**
Added index.html, style.css, and test.md file which are the requirements of the project.

### Requirements

- Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
- Create a new GitHub repo.
- Create a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
- Add a `.gitignore` file.
- Add `node_modules` to gitignore file.
- Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
- Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- Add 3 files (each one in a separate commit):
    - A .html file that includes a header with the text "Hello Microverse!". Use the `h1` tag for that.
    - A .css file that includes one class with styles for your header (make it in your favorite color).
    - A test.md file with the text "This file should be ignored by git".
- Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
- Open a pull request.

### CODE REVIEW

**Review by Strangeal — CHANGES_REQUESTED** [review]
Hi @asadmisrani, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text
## Required Changes ♻️

- [ ] Please include the files you have in the `development` branch in the `feature` branch so they can be reviewed. These files include `test.md`, `index.html`, and `README.md`.

- [ ] Please add `test.md` in the `gitignore` file as per project requirements.

- [ ] Please write a descriptive pull request summary of what you implemented in the project. Please don't recopy the project requirements as your pull request summary.

- [ ] Please use the complete `README.md` [template](https://github.com/microverseinc/readme-template) provided by Microverse and customize it to include all relevant parts.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by asadmisrani** [comment]
I already include the files from the development branch in the feature branch test.md, index.html, and README.md.

I add test.md in the gitignore file as per project requirements.

I already write a descriptive pull request summary of what you implemented in the project.

I have to write README.md template provided by Microverse and I also customize it to include all relevant parts.

**Comment by asadmisrani** [comment]
I already include the files from the development branch in the feature
branch test.md, index.html, and README.md.

I add test.md in the gitignore file as per project requirements.

I already write a descriptive pull request summary of what you implemented
in the project.

I have to write README.md template provided by Microverse and I also
customize it to include all relevant parts.

**Review by Eternalgratis — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 
Hi @asadmisrani , 

In my opinion, your project is ready for submission!  There is nothing else to say other than... it's time to merge it :shipit: 


Great Job and Happy coding! 🎉 
Developer-512px-10


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
